/* ═══ PHRASE DATABASE (30 phrases) ═══ */
const PHRASES = [
  { id:"e1", category:"email", japanese:"お世話になっております。", romaji:"Osewa ni natte orimasu.", english:"Thank you for your continued support. (Standard email/call opener to external contacts)", formality:"very_formal", context:"Use this as the FIRST LINE of every business email to people outside your company. It's mandatory — skipping it feels rude to Japanese colleagues.", example:"株式会社〇〇　山田様\nお世話になっております。\nQualitex Trading の Zain と申します。", tags:["email","greeting","external","opener","osewa"] },
  { id:"e2", category:"email", japanese:"お疲れ様です。", romaji:"Otsukaresama desu.", english:"Good work / Hello (internal greeting between colleagues)", formality:"formal", context:"Use this when greeting colleagues internally — in emails, Slack, passing in the hallway, or at the end of the day. Never use this to clients — use お世話になっております instead.", example:"（社内メール）\nお疲れ様です。営業部の田中です。\n明日の会議の件でご連絡しました。", tags:["email","greeting","internal","colleagues","otsukare"] },
  { id:"e3", category:"email", japanese:"お世話になります。初めてご連絡いたします。", romaji:"Osewa ni narimasu. Hajimete go-renraku itashimasu.", english:"Thank you. This is my first time contacting you.", formality:"very_formal", context:"Use this when emailing someone for the very first time. Combine with your name and company introduction on the next line.", example:"突然のご連絡、失礼いたします。\nQualitex Trading LLC の Zain と申します。\nこの度は貴社のサービスについてお伺いしたく、ご連絡いたしました。", tags:["email","first contact","introduction","external"] },
  { id:"e4", category:"email", japanese:"ご確認のほど、よろしくお願いいたします。", romaji:"Go-kakunin no hodo, yoroshiku onegai itashimasu.", english:"Please review / Please confirm at your convenience.", formality:"very_formal", context:"Standard email closing when you need someone to check or confirm something. Very common — use it almost every time you send a document or request.", example:"添付のファイルをご確認のほど、よろしくお願いいたします。", tags:["email","closing","confirm","request","yoroshiku"] },
  { id:"e5", category:"email", japanese:"取り急ぎ、ご連絡まで。", romaji:"Tori isogi, go-renraku made.", english:"I'm writing in haste / Quick note for now.", formality:"formal", context:"Use this at the END of a short, quick email when you don't have time to write a full message. It signals urgency and brevity — Japanese readers understand immediately.", example:"詳細は後ほどお送りします。\n取り急ぎ、ご連絡まで。", tags:["email","closing","quick","urgent"] },
  { id:"m1", category:"meeting", japanese:"よろしくお願いいたします。", romaji:"Yoroshiku onegai itashimasu.", english:"I'm counting on you / Please take care of this / Nice to meet you (context-dependent)", formality:"very_formal", context:"The most versatile phrase in Japanese business. Use it: at the end of introductions, when asking for help, closing emails, starting meetings, and almost any cooperative situation.", example:"本日はお時間をいただきありがとうございます。\nどうぞよろしくお願いいたします。", tags:["meeting","universal","yoroshiku","introduction","request"] },
  { id:"m2", category:"meeting", japanese:"ご説明いただけますか？", romaji:"Go-setsumei itadakemasu ka?", english:"Could you please explain that?", formality:"formal", context:"Polite way to ask for clarification in a meeting. Much softer than 「説明してください」. Use when you don't understand something a senior colleague or client said.", example:"恐れ入りますが、もう少し詳しくご説明いただけますか？", tags:["meeting","question","clarification","polite"] },
  { id:"m3", category:"meeting", japanese:"おっしゃる通りです。", romaji:"Ossharu toori desu.", english:"You are absolutely right. / That's exactly correct.", formality:"very_formal", context:"Use this to agree with a superior or client in a meeting. Much more respectful than 「そうですね」. Shows you are listening and value their opinion.", example:"おっしゃる通りです。その点については、早急に対応いたします。", tags:["meeting","agreement","respect","senior"] },
  { id:"m4", category:"meeting", japanese:"少々お時間をいただけますか？", romaji:"Shōshō ojikan wo itadakemasu ka?", english:"Could I have a moment of your time?", formality:"formal", context:"Use this before asking a busy colleague or boss a question. It's polite and signals you respect their time. Works in person and in chat messages.", example:"山田部長、少々お時間をいただけますか？\n先日の件でご相談があります。", tags:["meeting","time","asking","boss","colleague"] },
  { id:"m5", category:"meeting", japanese:"以上で、私からの報告は終わります。", romaji:"Ijō de, watashi kara no hōkoku wa owarimasu.", english:"That concludes my report / That's all from me.", formality:"formal", context:"Use this to formally end your presentation or report in a meeting. Clean, professional, and expected in Japanese business settings.", example:"以上で、第3四半期の売上報告を終わります。\nご質問はございますか？", tags:["meeting","presentation","closing","report"] },
  { id:"p1", category:"phone", japanese:"はい、〇〇会社の〇〇でございます。", romaji:"Hai, [company]-sha no [name] de gozaimasu.", english:"Hello, this is [Name] from [Company].", formality:"very_formal", context:"ALWAYS answer business calls this way. Never just say 「はい」alone. Replace 〇〇 with your company name and your name. This is mandatory in Japanese business phone culture.", example:"はい、Qualitex Trading の Zain でございます。\nいつもお世話になっております。", tags:["phone","answering","introduction","mandatory"] },
  { id:"p2", category:"phone", japanese:"少々お待ちくださいませ。", romaji:"Shōshō omachi kudasaimase.", english:"Please hold for a moment.", formality:"very_formal", context:"Use this before putting someone on hold or before going to find a colleague. Always say this — never just go silent on the phone.", example:"担当者に代わりますので、少々お待ちくださいませ。", tags:["phone","hold","wait","transfer"] },
  { id:"p3", category:"phone", japanese:"恐れ入りますが、もう一度おっしゃっていただけますか？", romaji:"Osoreirimasu ga, mō ichido osshatte itadakemasu ka?", english:"I'm sorry, could you please say that again?", formality:"very_formal", context:"The polite way to ask someone to repeat themselves on the phone. 「恐れ入りますが」is a softener — always add it before requests on the phone.", example:"恐れ入りますが、お名前をもう一度おっしゃっていただけますか？", tags:["phone","repeat","clarification","didn't hear"] },
  { id:"p4", category:"phone", japanese:"〇〇はただいま外出しております。", romaji:"[Name] wa tadaima gaishutsu shite orimasu.", english:"[Name] is currently out of the office.", formality:"very_formal", context:"Use this when someone calls for a colleague who is away. Follow with: 「よろしければ、ご伝言を承ります。」(Shall I take a message?)", example:"申し訳ございません、田中はただいま外出しております。\nよろしければ、ご伝言を承りますが、いかがでしょうか？", tags:["phone","absent","message","colleague"] },
  { id:"j1", category:"interview", japanese:"本日はお時間をいただき、誠にありがとうございます。", romaji:"Honjitsu wa ojikan wo itadaki, makoto ni arigatō gozaimasu.", english:"Thank you very much for taking the time to meet with me today.", formality:"very_formal", context:"Open your job interview with this line. It immediately shows respect and proper keigo ability — which Japanese interviewers notice and appreciate from foreign candidates.", example:"本日はお時間をいただき、誠にありがとうございます。\n〇〇と申します。どうぞよろしくお願いいたします。", tags:["interview","opening","thank you","first impression"] },
  { id:"j2", category:"interview", japanese:"〇〇と申します。どうぞよろしくお願いいたします。", romaji:"[Name] to mōshimasu. Dōzo yoroshiku onegai itashimasu.", english:"My name is [Name]. I look forward to working with you.", formality:"very_formal", context:"The humble form of self-introduction. 「申します」is the humble form of 「言います」. Always use this instead of 「私は〇〇です」in formal settings.", example:"はじめまして。Zain Rehman と申します。\nパキスタン出身で、現在神奈川県に在住しております。\nどうぞよろしくお願いいたします。", tags:["interview","introduction","name","humble form"] },
  { id:"j3", category:"interview", japanese:"御社の〇〇に大変興味を持っております。", romaji:"Onsha no [aspect] ni taihen kyōmi wo motte orimasu.", english:"I am very interested in your company's [aspect].", formality:"very_formal", context:"Use 「御社」(onsha) when SPEAKING about the company you're interviewing at. Use 「貴社」(kisha) when WRITING about them in emails/cover letters. This distinction is critical.", example:"御社のグローバルな事業展開に大変興味を持っております。\n特に、アジア市場への戦略について学びたいと考えております。", tags:["interview","interest","company","onsha vs kisha"] },
  { id:"j4", category:"interview", japanese:"ご質問いただき、ありがとうございます。", romaji:"Go-shitsumon itadaki, arigatō gozaimasu.", english:"Thank you for your question.", formality:"very_formal", context:"Say this BEFORE answering a question in an interview. It buys you 2-3 seconds to think, and it shows composure and respect. Japanese interviewers love this.", example:"ご質問いただき、ありがとうございます。\nその点についてですが、私は〇〇と考えております。", tags:["interview","answering","question","composure"] },
  { id:"t1", category:"thanks_apology", japanese:"大変お世話になりました。", romaji:"Taihen osewa ni narimashita.", english:"Thank you so much for everything you've done for me.", formality:"very_formal", context:"Use this when leaving a company, ending a long project, or thanking someone who has helped you significantly over time. Much stronger than a simple ありがとう.", example:"この度は大変お世話になりました。\n今後ともどうぞよろしくお願いいたします。", tags:["thanks","farewell","gratitude","deep thanks"] },
  { id:"t2", category:"thanks_apology", japanese:"大変申し訳ございません。", romaji:"Taihen mōshiwake gozaimasen.", english:"I am terribly sorry. (Deepest level of apology)", formality:"very_formal", context:"The most serious apology in Japanese business. Use for significant mistakes — missed deadlines, wrong information sent to clients, or any situation requiring a formal apology. Do NOT overuse.", example:"この度は弊社の不手際により、多大なご迷惑をおかけし、\n大変申し訳ございません。", tags:["apology","sorry","serious","mistake","formal"] },
  { id:"t3", category:"thanks_apology", japanese:"ご迷惑をおかけして、申し訳ありませんでした。", romaji:"Go-meiwaku wo okake shite, mōshiwake arimasen deshita.", english:"I apologize for the inconvenience I caused.", formality:"formal", context:"Mid-level apology for causing trouble or inconvenience. Good for everyday situations like being late to a meeting, a delayed response, or a minor error.", example:"返信が遅くなり、ご迷惑をおかけして、\n申し訳ありませんでした。", tags:["apology","inconvenience","late","delay"] },
  { id:"r1", category:"request", japanese:"〇〇していただけますでしょうか？", romaji:"[Action] shite itadakemasu deshō ka?", english:"Would you be able to [do something] for me?", formality:"very_formal", context:"The most polite way to make a request in Japanese business. The double-softening (〜ていただけます + でしょうか) makes it very gentle. Use with superiors and clients.", example:"資料をご確認していただけますでしょうか？\nお手すきの際にご対応いただければ幸いです。", tags:["request","asking","polite","superior","client"] },
  { id:"r2", category:"request", japanese:"お手すきの際に、ご対応いただければ幸いです。", romaji:"Otesuki no sai ni, go-taiō itadakereba saiwai desu.", english:"When you have a free moment, I would be grateful if you could handle this.", formality:"very_formal", context:"Add this after any request to soften it and show you respect the other person's time. One of the most professional phrases you can use — shows high keigo ability.", example:"添付の書類をご確認いただき、\nお手すきの際に、ご対応いただければ幸いです。", tags:["request","when free","soften","professional","time"] },
  { id:"r3", category:"request", japanese:"ご検討のほど、よろしくお願いいたします。", romaji:"Go-kentō no hodo, yoroshiku onegai itashimasu.", english:"I would appreciate your consideration on this matter.", formality:"very_formal", context:"Use this when submitting a proposal, asking for approval, or requesting a decision. It's softer than demanding an answer — it respects the other person's process.", example:"ご多忙の中、誠に恐縮ですが、\nご検討のほど、よろしくお願いいたします。", tags:["request","proposal","approval","consideration"] },
  { id:"o1", category:"office", japanese:"ご報告いたします。", romaji:"Go-hōkoku itashimasu.", english:"I would like to report / I have an update for you.", formality:"formal", context:"Use this to open any update or status report to your boss or team. Signals you are about to give important information — gets their attention immediately.", example:"部長、少々よろしいでしょうか。\n〇〇プロジェクトの件でご報告いたします。", tags:["office","report","update","boss","status"] },
  { id:"o2", category:"office", japanese:"承知いたしました。", romaji:"Shōchi itashimashita.", english:"Understood. / I will take care of it.", formality:"very_formal", context:"The most professional way to say 'understood' to a superior. NEVER say 「了解です」to your boss — it's considered too casual. Always use 「承知いたしました」instead.", example:"部長：「この資料、明日までにお願いします。」\nあなた：「承知いたしました。明日の午前中にお送りします。」", tags:["office","understood","confirmed","boss","承知 vs 了解"] },
  { id:"o3", category:"office", japanese:"確認させていただきます。", romaji:"Kakunin sasete itadakimasu.", english:"Let me confirm / I will check on that.", formality:"formal", context:"Use when you need to verify something before giving an answer. Buying time professionally — much better than saying 「わかりません」(I don't know).", example:"その件については、確認させていただきます。\n本日中にご回答いたします。", tags:["office","confirm","check","buy time","professional"] },
  { id:"n1", category:"firstday", japanese:"本日よりお世話になります。〇〇と申します。", romaji:"Honjitsu yori osewa ni narimasu. [Name] to mōshimasu.", english:"Starting today, I am in your care. My name is [Name].", formality:"very_formal", context:"Say this on your FIRST DAY at a new job when introducing yourself to the team. It's the standard new-employee self-introduction opener. Bow slightly as you say it.", example:"皆さん、本日よりお世話になります。\nZain Rehman と申します。\n未熟ではございますが、精一杯頑張りますので、\nどうぞよろしくお願いいたします。", tags:["first day","introduction","new employee","onboarding"] },
  { id:"n2", category:"firstday", japanese:"お先に失礼いたします。", romaji:"Osaki ni shitsurei itashimasu.", english:"Excuse me for leaving before you. (Said when leaving the office before colleagues)", formality:"formal", context:"ALWAYS say this when you leave the office before your colleagues. Leaving without saying this is considered rude. Colleagues will respond with 「お疲れ様でした」.", example:"（帰り際に）\nお先に失礼いたします。\n（同僚の返事）お疲れ様でした。", tags:["first day","leaving office","daily","etiquette","mandatory"] },
  { id:"n3", category:"firstday", japanese:"ただいま戻りました。", romaji:"Tadaima modorimashita.", english:"I'm back. (Said when returning to the office)", formality:"formal", context:"Say this when you return to the office after going out (lunch, client visit, errand). Colleagues will respond with 「お帰りなさい」. It's a small but important daily ritual.", example:"（外出から戻って）\nただいま戻りました。\n（同僚の返事）お帰りなさい。", tags:["first day","returning","daily","etiquette"] }
];

const CATEGORIES = [
  { id:"email", emoji:"📧", jp:"メール・挨拶", en:"Email & Greetings" },
  { id:"meeting", emoji:"📋", jp:"会議・打ち合わせ", en:"Meetings" },
  { id:"phone", emoji:"📞", jp:"電話対応", en:"Phone Calls" },
  { id:"interview", emoji:"💼", jp:"面接・自己紹介", en:"Job Interviews" },
  { id:"thanks_apology", emoji:"🙏", jp:"お礼・謝罪", en:"Thanks & Apologies" },
  { id:"request", emoji:"🙇", jp:"依頼・お願い", en:"Requests & Asking Favors" },
  { id:"office", emoji:"🏢", jp:"社内コミュニケーション", en:"Internal Office Talk" },
  { id:"firstday", emoji:"🌅", jp:"入退社・初日", en:"First Day / Onboarding" }
];

const FORMALITY_LABELS = {
  very_formal: "Very Formal",
  formal: "Formal",
  casual: "Casual"
};

const FORMALITY_FILTERS = [
  { id: "all", label: "All" },
  { id: "very_formal", label: "Very Formal" },
  { id: "formal", label: "Formal" },
  { id: "casual", label: "Casual" }
];